"""Implement many-to-many relationship between users and personas

Revision ID: 6cc7ac4092b2
Revises: 3d20eaece3d3
Create Date: 2025-11-04 16:58:27.100808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cc7ac4092b2'
down_revision = '3d20eaece3d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=False)

    op.create_table('user_persona_assignments',
    sa.Column('assignment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.persona_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index('ix_user_persona_assignments_user_id_persona_id', 'user_persona_assignments', ['user_id', 'persona_id'], unique=True)

    op.drop_index('ix_user_profiles_persona_id', table_name='user_profiles')
    op.drop_column('user_profiles', 'persona_id')
    op.drop_column('user_profiles', 'persona_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('persona_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_user_profiles_persona_id', 'user_profiles', ['persona_id'], unique=False)

    op.drop_index('ix_user_persona_assignments_user_id_persona_id', table_name='user_persona_assignments')
    op.drop_table('user_persona_assignments')
    
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###

