"""description

Revision ID: 9a34438a9f36
Revises: 001_initial
Create Date: 2025-11-03 14:55:24.411592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a34438a9f36'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profiles_user_id_key', 'user_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_profiles_user_id_key', 'user_profiles', ['user_id'])
    # ### end Alembic commands ###

